// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZSuGL_x-py5sbGHepsDD0V1NsnJUcJx0',
    appId: '1:634756522150:web:a7351daf332e20fba45467',
    messagingSenderId: '634756522150',
    projectId: 'telicash',
    authDomain: 'telicash.firebaseapp.com',
    storageBucket: 'telicash.appspot.com',
    measurementId: 'G-TMR9HP75D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBqfLGR1h9xbw0r64Oti9317axw0uOhek',
    appId: '1:634756522150:android:0f4ed65934894adea45467',
    messagingSenderId: '634756522150',
    projectId: 'telicash',
    storageBucket: 'telicash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuU29nSRdG58rXM8udgOTNHreN3JSlWU0',
    appId: '1:634756522150:ios:8f21f3498d960aeba45467',
    messagingSenderId: '634756522150',
    projectId: 'telicash',
    storageBucket: 'telicash.appspot.com',
    iosBundleId: 'com.teliuser.alivestation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuU29nSRdG58rXM8udgOTNHreN3JSlWU0',
    appId: '1:634756522150:ios:c98c9bfb80d62cb5a45467',
    messagingSenderId: '634756522150',
    projectId: 'telicash',
    storageBucket: 'telicash.appspot.com',
    iosBundleId: 'com.teliuser.alivestation.RunnerTests',
  );
}
