name: schoolbusapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/schoolbus.png
    - lib/assets/back_school_station.png
    - lib/assets/go1.png
    - lib/assets/backtoschool.jpeg
    - lib/assets/succesfulchildwithcap.jpeg
    - lib/assets/gmail1.png
    - lib/assets/manpic.png
    # - lib/assets/page-1/images/vector-tQh.png
    # - lib/assets/page-1/images/vector-Rnh.png
    # - lib/assets/page-1/images/group-64.png
    # - lib/assets/page-1/images/battery.png
    # - lib/assets/page-1/images/vector-92H.png
    # - lib/assets/page-1/images/wi-fi.png
    # - lib/assets/page-1/images/battery-Ljb.png
    # - lib/assets/page-1/images/vector-kzD.png
    # - lib/assets/page-1/images/combined-shape-CPb.png
    # - lib/assets/page-1/images/vector-stroke.png
    # - lib/assets/page-1/images/group-71.png
    # - lib/assets/page-1/images/icon-outlined-application-download.png
    # - lib/assets/page-1/images/combined-shape-upu.png
    # - lib/assets/page-1/images/battery-21f.png
    # - lib/assets/page-1/images/calendar-vYH.png
    # - lib/assets/page-1/images/group-34002.png
    # - lib/assets/page-1/images/vector-hRb.png
    # - lib/assets/page-1/images/battery-LPK.png
    # - lib/assets/page-1/images/group-33813.png
    # - lib/assets/page-1/images/wi-fi-zuf.png
    # - lib/assets/page-1/images/wi-fi-qbP.png
    # - lib/assets/page-1/images/group-33813-x2D.png
    # - lib/assets/page-1/images/wifi.png
    # - lib/assets/page-1/images/vector-uzZ.png
    # - lib/assets/page-1/images/group-33813-8F3.png
    # - lib/assets/page-1/images/calendar-FCV.png
    # - lib/assets/page-1/images/vector-Thj.png
    # - lib/assets/page-1/images/wi-fi-6fT.png
    # - lib/assets/page-1/images/vector-HEh.png
    # - lib/assets/page-1/images/rectangle-15.png
    # - lib/assets/page-1/images/battery-f6h.png
    # - lib/assets/page-1/images/ellipse-6.png
    # - lib/assets/page-1/images/group-33813-J3j.png
    # - lib/assets/page-1/images/ellipse-579-bg.png
    # - lib/assets/page-1/images/ellipse-579-bg-GCq.png
    # - lib/assets/page-1/images/group-66.png
    # - lib/assets/page-1/images/gmail-1.png
    # - lib/assets/page-1/images/cashless-payment-1.png
    # - lib/assets/page-1/images/battery-8Eu.png
    # - lib/assets/page-1/images/wi-fi-RNy.png
    # - lib/assets/page-1/images/combined-shape-uu3.png
    # - lib/assets/page-1/images/u-moon.png
    # - lib/assets/page-1/images/auto-group-v5lz.png
    # - lib/assets/page-1/images/heart.png
    # - lib/assets/page-1/images/battery-KZb.png
    # - lib/assets/page-1/images/rectangle-15-Jr5.png
    # - lib/assets/page-1/images/report-1.png
    # - lib/assets/page-1/images/wi-fi-MKf.png
    # - lib/assets/page-1/images/bus-1.png
    # - lib/assets/page-1/images/setting-1.png
    # - lib/assets/page-1/images/rectangle-15-yf7.png
    # - lib/assets/page-1/images/setting-1-Ts7.png
    # - lib/assets/page-1/images/vector-cED.png
    # - lib/assets/page-1/images/setting-1-7PF.png
    # - lib/assets/page-1/images/wi-fi-Juo.png
    # - lib/assets/page-1/images/group-33813-vL9.png
    # - lib/assets/page-1/images/unnamed1-removebg-preview-2.png
    # - lib/assets/page-1/images/unnamed1-removebg-preview-2-mLm.png
    # - lib/assets/page-1/images/vector-7ow.png
    # - lib/assets/page-1/images/unnamed1-removebg-preview-1.png
    # - lib/assets/page-1/images/down-button.png
    # - lib/assets/page-1/images/unnamed1-removebg-preview-1-hn1.png
    # - lib/assets/page-1/images/unnamed1-removebg-preview-1-YyX.png
    # - lib/assets/page-1/images/combined-shape-ct1.png
    # - lib/assets/page-1/images/combined-shape-Z3w.png
    # - lib/assets/page-1/images/group-33813-tC1.png
    # - lib/assets/page-1/images/wi-fi-BaR.png
    # - lib/assets/page-1/images/alarm-bell-1.png
    # - lib/assets/page-1/images/alarm-bell-1-FxD.png
    # - lib/assets/page-1/images/setting-1-Mr9.png
    # - lib/assets/page-1/images/alarm-bell-1-1qT.png
    # - lib/assets/page-1/images/home.png
    # - lib/assets/page-1/images/group-70.png
    # - lib/assets/page-1/images/home-MZj.png
    # - lib/assets/page-1/images/alarm-bell-1-Vvq.png
    # - lib/assets/page-1/images/icon.png
    # - lib/assets/page-1/images/home-XkM.png
    # - lib/assets/page-1/images/alarm-bell-1-M4D.png
    # - lib/assets/page-1/images/calendar-oE9.png
    # - lib/assets/page-1/images/group-69.png
    # - lib/assets/page-1/images/setting-1-h7o.png
    # - lib/assets/page-1/images/rectangle-15-2NM.png
    # - lib/assets/page-1/images/home-nAV.png
    # - lib/assets/page-1/images/wi-fi-ZRT.png
    # - lib/assets/page-1/images/combined-shape-jUM.png
    # - lib/assets/page-1/images/group-68.png
    # - lib/assets/page-1/images/home-Lu7.png
    # - lib/assets/page-1/images/combined-shape-MF7.png
    # - lib/assets/page-1/images/alarm-bell-1-dQu.png
    # - lib/assets/page-1/images/vector-YGy.png
    # - lib/assets/page-1/images/live-streaming-1.png
    # - lib/assets/page-1/images/wi-fi-T5b.png
    # - lib/assets/page-1/images/vector-stroke-ZyB.png
    # - lib/assets/page-1/images/battery-mrH.png
    # - lib/assets/page-1/images/calendar-En5.png
    # - lib/assets/page-1/images/bg.png
    # - lib/assets/page-1/images/vector-oVB.png
    # - lib/assets/page-1/images/rectangle-15-Agy.png
    # - lib/assets/page-1/images/wi-fi-V4M.png
    # - lib/assets/page-1/images/go-1.png
    # - lib/assets/page-1/images/setting-1-Pb7.png
    # - lib/assets/page-1/images/alarm-bell-1-KDB.png
    # - lib/assets/page-1/images/battery-GYy.png
    # - lib/assets/page-1/images/combined-shape-wLu.png
    # - lib/assets/page-1/images/combined-shape-RzZ.png
    # - lib/assets/page-1/images/home-1xV.png
    # - lib/assets/page-1/images/calendar-iW5.png
    # - lib/assets/page-1/images/translate.png
    # - lib/assets/page-1/images/wi-fi-fsf.png
    # - lib/assets/page-1/images/rectangle-3.png
    # - lib/assets/page-1/images/vector-jfo.png
    # - lib/assets/page-1/images/battery-GpH.png
    # - lib/assets/page-1/images/group-67.png
    # - lib/assets/page-1/images/home-xjs.png
    # - lib/assets/page-1/images/wi-fi-wPP.png
    # - lib/assets/page-1/images/vector-stroke-7UD.png
    # - lib/assets/page-1/images/vector-GM7.png
    # - lib/assets/page-1/images/vector-stroke-Dn9.png
    # - lib/assets/page-1/images/toc.png
    # - lib/assets/page-1/images/setting-1-G17.png
    # - lib/assets/page-1/images/vector-TK7.png
    # - lib/assets/page-1/images/combined-shape-3YD.png
    # - lib/assets/page-1/images/setting-1-vru.png
    # - lib/assets/page-1/images/alarm-bell-1-6Fb.png
    # - lib/assets/page-1/images/group-33930.png
    # - lib/assets/page-1/images/battery-GZF.png
    # - lib/assets/page-1/images/ellipse-2-bg.png
    # - lib/assets/page-1/images/vector-Aed.png
    # - lib/assets/page-1/images/vector-jSq.png
    # - lib/assets/page-1/images/setting-1-bxD.png
    # - lib/assets/page-1/images/ellipse-580-bg.png
    # - lib/assets/page-1/images/calendar-VA1.png
    # - lib/assets/page-1/images/rectangle-15-5ZB.png
    # - lib/assets/page-1/images/combined-shape-GXB.png
    # - lib/assets/page-1/images/alarm-bell-1-2aD.png
    # - lib/assets/page-1/images/vector-stroke-upd.png
    # - lib/assets/page-1/images/combined-shape-5v1.png
    # - lib/assets/page-1/images/calendar-uiy.png
    # - lib/assets/page-1/images/vector-wxV.png
    # - lib/assets/page-1/images/vector-vC9.png
    # - lib/assets/page-1/images/ellipse-46.png
    # - lib/assets/page-1/images/home-BJH.png
    # - lib/assets/page-1/images/rectangle-15-iws.png
    # - lib/assets/page-1/images/group-65.png
    # - lib/assets/page-1/images/vector-stroke-r1f.png
    # - lib/assets/page-1/images/money-1.png
    # - lib/assets/page-1/images/battery-iE5.png
    # - lib/assets/page-1/images/setting-1-WBj.png
    # - lib/assets/page-1/images/bus-1-1.png
    # - lib/assets/page-1/images/payment-method-1.png
    # - lib/assets/page-1/images/vector-2PT.png
    # - lib/assets/page-1/images/vector-stroke-Xnh.png
    # - lib/assets/page-1/images/location-1-1.png
    # - lib/assets/page-1/images/wi-fi-4J5.png
    # - lib/assets/page-1/images/wi-fi-Fub.png
    # - lib/assets/page-1/images/on-button-1.png
    # - lib/assets/page-1/images/battery-gHF.png
    # - lib/assets/page-1/images/rectangle-15-CvM.png
    # - lib/assets/page-1/images/calendar-YTb.png
    # - lib/assets/page-1/images/battery-qk5.png
    # - lib/assets/page-1/images/setting-1-oZb.png
    # - lib/assets/page-1/images/rectangle-15-83T.png
    # - lib/assets/page-1/images/rectangle-15-ppZ.png
    # - lib/assets/page-1/images/wi-fi-KEq.png
    # - lib/assets/page-1/images/group.png
    # - lib/assets/page-1/images/vector-r6V.png
    # - lib/assets/page-1/images/vector-LpZ.png
    # - lib/assets/page-1/images/combined-shape-oqs.png
    # - lib/assets/page-1/images/rectangle.png
    # - lib/assets/page-1/images/home-ipq.png
    # - lib/assets/page-1/images/battery-iS5.png
    # - lib/assets/page-1/images/ellipse-579-bg-H7w.png
    # - lib/assets/page-1/images/setting-1-6ND.png
    # - lib/assets/page-1/images/back-school-stationery-education-element-empty-banner-cartoon-yellow-background-3d-illustration-1-bg.png
    # - lib/assets/page-1/images/wi-fi-99b.png
    # - lib/assets/page-1/images/rectangle-15-2KK.png
    # - lib/assets/page-1/images/home-d1b.png
    # - lib/assets/page-1/images/urban-transport-paper-style-arrangement-1.png
    # - lib/assets/page-1/images/down-button-ReZ.png
    # - lib/assets/page-1/images/group-mQV.png
    # - lib/assets/page-1/images/home-VMb.png
    # - lib/assets/page-1/images/battery-xqP.png
    # - lib/assets/page-1/images/home-dcM.png
    # - lib/assets/page-1/images/ellipse-579-bg-bBf.png
    # - lib/assets/page-1/images/combined-shape-WDX.png
    # - lib/assets/page-1/images/vector-stroke-6jT.png
    # - lib/assets/page-1/images/group-oGV.png
    # - lib/assets/page-1/images/group-xW5.png
    # - lib/assets/page-1/images/calendar-Rfo.png
    # - lib/assets/page-1/images/vector-SYH.png
    # - lib/assets/page-1/images/combined-shape-Faq.png
    # - lib/assets/page-1/images/ellipse-579-bg-gUH.png
    # - lib/assets/page-1/images/vector-stroke-tim.png
    # - lib/assets/page-1/images/combined-shape-h7o.png
    # - lib/assets/page-1/images/alarm-bell-1-wsw.png
    # - lib/assets/page-1/images/ellipse-45.png
    # - lib/assets/page-1/images/down-button-Pbw.png
    # - lib/assets/page-1/images/setting-1-4nm.png
    # - lib/assets/page-1/images/calendar-qW1.png
    # - lib/assets/page-1/images/vector-Er5.png
    # - lib/assets/page-1/images/group-ycd.png
    # - lib/assets/page-1/images/group-KqT.png
    # - lib/assets/page-1/images/group-keD.png
    # - lib/assets/page-1/images/vector-kyX.png
    # - lib/assets/page-1/images/down-button-Gph.png
    # - lib/assets/page-1/images/alarm-bell-1-1fX.png
    # - lib/assets/page-1/images/battery-iNM.png
    # - lib/assets/page-1/images/vector-pwB.png
    # - lib/assets/page-1/images/group-Ymf.png
    # - lib/assets/page-1/images/group-FbX.png
    # - lib/assets/page-1/images/calendar-LKK.png
    # - lib/assets/page-1/images/pocess-icon.png
    # - lib/assets/page-1/images/combined-shape-L6M.png
    # - lib/assets/page-1/images/group-gR7.png
    # - lib/assets/page-1/images/group-S9P.png
    # - lib/assets/page-1/images/rectangle-15-w69.png
    # - lib/assets/page-1/images/group-sNR.png
    # - lib/assets/page-1/images/rectangle-15-QNM.png
    # - lib/assets/page-1/images/alarm-bell-1-HAZ.png
    # - lib/assets/page-1/images/alarm-bell-1-FWh.png
    # - lib/assets/page-1/images/group-TTf.png
    # - lib/assets/page-1/images/ellipse-44.png
    # - lib/assets/page-1/images/alarm-bell-1-B4D.png
    # - lib/assets/page-1/images/vector-pmP.png
    # - lib/assets/page-1/images/wi-fi-v3j.png
    # - lib/assets/page-1/images/group-szZ.png
    # - lib/assets/page-1/images/group-LdF.png
    # - lib/assets/page-1/images/vector-stroke-e89.png
    # - lib/assets/page-1/images/vector-omj.png
    # - lib/assets/page-1/images/home-Sph.png
    # - lib/assets/page-1/images/vector-P8D.png
    # - lib/assets/page-1/images/vector-85o.png
    # - lib/assets/page-1/images/combined-shape-NAM.png
    # - lib/assets/page-1/images/successful-child-with-graduation-cap-backpack-full-books-1.png
    # - lib/assets/page-1/images/vector-40.png
    # - lib/assets/page-1/images/calendar-rP3.png
    # - lib/assets/page-1/images/placeholder-2.png
    # - lib/assets/page-1/images/group-hvh.png
    # - lib/assets/page-1/images/placeholder-1.png
    # - lib/assets/page-1/images/group-aVo.png
    # - lib/assets/page-1/images/vector-stroke-aXs.png
    # - lib/assets/page-1/images/map.png
    # - lib/assets/page-1/images/ellipse-163.png
    # - lib/assets/page-1/images/battery-dfo.png
    # - lib/assets/page-1/images/pocess-icon-JH7.png
    # - lib/assets/page-1/images/group-PxV.png
    # - lib/assets/page-1/images/ellipse-2-bg-kjT.png
    # - lib/assets/page-1/images/battery-bGD.png
    # - lib/assets/page-1/images/home-Uws.png
    # - lib/assets/page-1/images/wi-fi-31B.png
    # - lib/assets/page-1/images/calendar-L9w.png
    # - lib/assets/page-1/images/wi-fi-izM.png
    # - lib/assets/page-1/images/bus-1-1-XAy.png
    # - lib/assets/page-1/images/group-aAV.png
    # - lib/assets/page-1/images/battery-W9F.png
    # - lib/assets/page-1/images/setting-1-iyP.png
    # - lib/assets/page-1/images/rectangle-15-4Kb.png
    # - lib/assets/page-1/images/pocess-icon-bk5.png
    # - lib/assets/page-1/images/pocess-icon-N2M.png
    # - lib/assets/page-1/images/floating-button-normal.png
    # - lib/assets/page-1/images/avatar.png
    # - lib/assets/page-1/images/icon-chevron-right.png
    # - lib/assets/page-1/images/group-wRB.png
    # - lib/assets/page-1/images/icon-chevron-right-Psf.png
    # - lib/assets/page-1/images/ellipse-164.png
    # - lib/assets/page-1/images/clock-1-1.png
    # - lib/assets/page-1/images/clock-1-2.png
    # - lib/assets/page-1/images/icon-chevron-right-nGy.png
    # - lib/assets/page-1/images/icon-chevron-right-GhP.png
    # - lib/assets/page-1/images/map-bg.png
    # - lib/assets/page-1/images/group-a33.png
    # - lib/assets/page-1/images/group-34037.png
    # - lib/assets/page-1/images/frame-2.png
    # - lib/assets/page-1/images/alarm-bell-1-7ah.png
    # - lib/assets/page-1/images/icon-chevron-right-GAd.png
    # - lib/assets/page-1/images/vector-rm7.png
    # - lib/assets/page-1/images/combined-shape-xL9.png
    # - lib/assets/page-1/images/vector-stroke-f2q.png
    # - lib/assets/page-1/images/wi-fi-oN1.png
    # - lib/assets/page-1/images/vector-stroke-PpV.png
    # - lib/assets/page-1/images/combined-shape-eFj.png
    # - lib/assets/page-1/images/vector-RyB.png
    # - lib/assets/page-1/images/new-contact.png
    # - lib/assets/page-1/images/user.png
    # - lib/assets/page-1/images/vector-wPf.png
    # - lib/assets/page-1/images/group-33907.png
    # - lib/assets/page-1/images/vector-stroke-qg5.png
    # - lib/assets/page-1/images/logout-1.png
    # - lib/assets/page-1/images/group-33899.png
    # - lib/assets/page-1/images/vector-d6Z.png
    # - lib/assets/page-1/images/vector-Gch.png
    # - lib/assets/page-1/images/vector-PSH.png
    # - lib/assets/page-1/images/battery-xU1.png
    # - lib/assets/page-1/images/vector-6aD.png
    # - lib/assets/page-1/images/wi-fi-yeZ.png
    # - lib/assets/page-1/images/helpline-1.png
    # - lib/assets/page-1/images/vector-Tvy.png
    # - lib/assets/page-1/images/battery-D69.png
    # - lib/assets/page-1/images/vector-YKK.png
    # - lib/assets/page-1/images/enable-1.png
    # - lib/assets/page-1/images/rectangle-15-v5X.png
    # - lib/assets/page-1/images/calendar-ZC5.png
    # - lib/assets/page-1/images/vector-JKj.png
    # - lib/assets/page-1/images/group-33899-4c9.png
    # - lib/assets/page-1/images/home-1ys.png
    # - lib/assets/page-1/images/ellipse-580-bg-UKT.png
    # - lib/assets/page-1/images/setting-1-Vzq.png
    # - lib/assets/page-1/images/phone-call-1.png
    # - lib/assets/page-1/images/ellipse-579-bg-sVj.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
